version: "3.3"
services:
  db:
    image: mysql
    # restart: always
    environment:
      MYSQL_DATABASE: "ccrt_clinic"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  api:
    image: rakibulrafi/ccrt_clinic:doctor_schedule_3
    # restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - "db"
volumes:
  my-db:
